version: "3.9"

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo1-data:/data/db
    networks:
      - backend

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: unless-stopped
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo2-data:/data/db
    networks:
      - backend

  python-app:
    image: mongo-python-app
    container_name: python-app
    restart: unless-stopped
    networks:
      - backend
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - python-app
    networks:
      - backend

volumes:
  mongo1-data:
  mongo2-data:

networks:
  backend:
    driver: bridge
